### ISSUE TITLE
Player Data out of date

### ISSUE THREAD

**Issue by tmulledy** [erythana/EVEye#2]
Seems that player data is not always updating. Had an occasion today where one player was showing as in a particular corp, and another in another corp. After jumping the explorer and getting killed by his cloaked Loki, turns out they are both in the same corp joined the same day (6 days ago) .. yet ES had not updated for one of them.

**Comment by erythana** [comment]
Hey, sorry for that!

Im pulling all my data from CCPs or ZKillboard Servers.
Unfortunately, CCPs endpoint for the Character Information caches data for up to 7 days, so might sometimes not up to date: 
https://esi.evetech.net/ui/#/Character/get_characters_character_id

**Comment by tmulledy** [comment]
No worries .. did not know that and thought it was weird that one of his toons was showing one and the other another. Keep up the great work LOVE ES!!!!!!!!!!
